version: '3.8'

services:
  employee-assessment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-assessment-app
    ports:
      - "80:5000"
      - "443:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DATABASE_PATH=/app/data/new_questions.db
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  nginx:
    image: ccr.ccs.tencentyun.com/library/nginx:alpine
    container_name: employee-assessment-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - employee-assessment
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
  app-logs:
  app-uploads:
